<Commands ExitAfterPlayback="true" PauseAfterPlaybackInMs="10" CommandIntervalInMs="20">
  <CreateNodeCommand NodeId="cc30b9cd-1884-47e0-9e17-1a14e3cd0c35" NodeName="Autodesk.DesignScript.Geometry.Point.Z" X="0" Y="0" DefaultPosition="true" TransformCoordinates="true" />
  <SelectModelCommand ModelGuid="cc30b9cd-1884-47e0-9e17-1a14e3cd0c35" Modifiers="0" />
  <DragSelectionCommand X="223" Y="276" DragOperation="0" />
  <DragSelectionCommand X="346" Y="271" DragOperation="1" />
  <SelectModelCommand ModelGuid="00000000-0000-0000-0000-000000000000" Modifiers="0" />
  <CreateNodeCommand NodeId="9f461702-7e8d-4d52-bd52-1199a556cbc0" NodeName="Code Block" X="117" Y="192" DefaultPosition="false" TransformCoordinates="true" />
  <SelectModelCommand ModelGuid="00000000-0000-0000-0000-000000000000" Modifiers="0" />
  <UpdateModelValueCommand ModelGuid="9f461702-7e8d-4d52-bd52-1199a556cbc0" Name="Code" Value="Point.ByCoordinates(x,0,0);" />
  <CreateNodeCommand NodeId="c0a70160-fb7e-4441-a06e-1e783d7c0d92" NodeName="Autodesk.DesignScript.Geometry.Point.X" X="0" Y="0" DefaultPosition="true" TransformCoordinates="true" />
  <SelectModelCommand ModelGuid="c0a70160-fb7e-4441-a06e-1e783d7c0d92" Modifiers="0" />
  <DragSelectionCommand X="182" Y="371" DragOperation="0" />
  <DragSelectionCommand X="349" Y="321" DragOperation="1" />
  <SelectModelCommand ModelGuid="cc30b9cd-1884-47e0-9e17-1a14e3cd0c35" Modifiers="0" />
  <DeleteModelCommand ModelGuid="00000000-0000-0000-0000-000000000000" />
  <MakeConnectionCommand NodeId="9f461702-7e8d-4d52-bd52-1199a556cbc0" PortIndex="0" Type="1" ConnectionMode="0" />
  <MakeConnectionCommand NodeId="c0a70160-fb7e-4441-a06e-1e783d7c0d92" PortIndex="0" Type="0" ConnectionMode="1" />
  <SelectModelCommand ModelGuid="c0a70160-fb7e-4441-a06e-1e783d7c0d92" Modifiers="0" />
  <DragSelectionCommand X="339" Y="312" DragOperation="0" />
  <DragSelectionCommand X="380" Y="291" DragOperation="1" />
  <SelectModelCommand ModelGuid="00000000-0000-0000-0000-000000000000" Modifiers="0" />
  <CreateNodeCommand NodeId="53ff4496-122b-4b72-9c2e-627bb85d4a43" NodeName="Code Block" X="7" Y="309" DefaultPosition="false" TransformCoordinates="true" />
  <SelectModelCommand ModelGuid="00000000-0000-0000-0000-000000000000" Modifiers="0" />
  <UpdateModelValueCommand ModelGuid="53ff4496-122b-4b72-9c2e-627bb85d4a43" Name="Code" Value="10" />
  <MakeConnectionCommand NodeId="53ff4496-122b-4b72-9c2e-627bb85d4a43" PortIndex="0" Type="1" ConnectionMode="0" />
  <MakeConnectionCommand NodeId="9f461702-7e8d-4d52-bd52-1199a556cbc0" PortIndex="0" Type="0" ConnectionMode="1" />
  <RunCancelCommand ShowErrors="false" CancelRun="false" />
  <PausePlaybackCommand Tag="Point-10" PauseDurationInMs="20" />
  <SelectModelCommand ModelGuid="00000000-0000-0000-0000-000000000000" Modifiers="0" />
  <UpdateModelValueCommand ModelGuid="53ff4496-122b-4b72-9c2e-627bb85d4a43" Name="Code" Value="2;" />
  <RunCancelCommand ShowErrors="false" CancelRun="false" />
  <PausePlaybackCommand Tag="Point-2" PauseDurationInMs="20" />
  <SelectModelCommand ModelGuid="00000000-0000-0000-0000-000000000000" Modifiers="0" />
  <UpdateModelValueCommand ModelGuid="9f461702-7e8d-4d52-bd52-1199a556cbc0" Name="Code" Value="Point.ByCoordinates(12,0,0);" />
  <RunCancelCommand ShowErrors="false" CancelRun="false" />
  <PausePlaybackCommand Tag="Point-12" PauseDurationInMs="200" />
  <SelectModelCommand ModelGuid="00000000-0000-0000-0000-000000000000" Modifiers="0" />
  <UpdateModelValueCommand ModelGuid="9f461702-7e8d-4d52-bd52-1199a556cbc0" Name="Code" Value="Point.ByCoordinates(-5,0,0);" />
  <RunCancelCommand ShowErrors="false" CancelRun="false" />
  <PausePlaybackCommand Tag="Point--5" PauseDurationInMs="200" />
</Commands>